import { NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Hero from '../components/Hero';
import About from '../components/About';
import WorkExperience from '../components/WorkExperience';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import ContactMe from '../components/ContactMe';

const Home: NextPage = () => {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar-thin scroll-smooth sm:scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#FFE55C]/60">
       <Head>
        <title>Varun Building</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      <Header />
      {/* hero */}
      <section  id="hero" className="snap-center">
        <Hero />
      </section>
      {/*about */}
      <section id="about" className="snap-center">
        <About />
      </section>
      {/*Work Experience */}
      <section id="experience" className='snap-center'>
        <WorkExperience />
      </section>
          {/* skills    */}
      <section id='skills' className="snap-center">
      <Skills />
      </section>
        <section id='projects' className='snap-center'>
          <Projects />
        </section>
      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>
      
        </div>
  );
}
export default Home;